import {
  ArchiveBoxIcon,
  ArrowLeftStartOnRectangleIcon,
  ArrowPathIcon,
  Bars3Icon,
  CheckIcon,
  ChevronDownIcon,
  DocumentTextIcon,
  EllipsisVerticalIcon,
  MoonIcon,
  NoSymbolIcon,
  PaintBrushIcon,
  PencilIcon,
  PlusIcon,
  Squares2X2Icon,
  SunIcon,
  SwatchIcon,
  TagIcon,
  TrashIcon,
  UserIcon,
  UserPlusIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'
import { ExclamationCircleIcon } from '@heroicons/react/24/solid'

export const icons = {
  notes: DocumentTextIcon,
  archive: ArchiveBoxIcon,
  trash: TrashIcon,
  pencil: PencilIcon,
  grid: Squares2X2Icon,
  list: Bars3Icon,
  close: XMarkIcon,
  check: CheckIcon,
  ellipsis: EllipsisVerticalIcon,
  logout: ArrowLeftStartOnRectangleIcon,
  user: UserIcon,
  'user-plus': UserPlusIcon,
  moon: MoonIcon,
  sun: SunIcon,
  'exclamation-circle': ExclamationCircleIcon,
  'chevron-down': ChevronDownIcon,
  swatch: SwatchIcon,
  'paint-brush': PaintBrushIcon,
  'no-symbol': NoSymbolIcon,
  tag: TagIcon,
  plus: PlusIcon,
  spinner: ArrowPathIcon,
}
