export default {
  SECRET_KEY: process.env.NEXT_PUBLIC_SECRET_KEY,
  DEFAULT_LANGUAGE: process.env.NEXT_PUBLIC_DEFAULT_LANGUAGE,
  DEFAULT_LOCALE: process.env.NEXT_PUBLIC_DEFAULT_LOCALE,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  APP_ENVIRONMENT: process.env.NEXT_PUBLIC_APP_ENVIRONMENT,
  MAIN_DOMAIN_NAME_FOR_COOKIE: process.env.NEXT_PUBLIC_MAIN_DOMAIN_NAME_FOR_COOKIE,
}
